import type { Metadata } from "next";
import { Inter, Calistoga } from 'next/font/google';
import "./globals.css";

const inter = Inter({
	subsets: ['latin'],
	variable: '--font-inter'
});

const calistoga = Calistoga({
	weight: '400',
	subsets: ['latin'],
	variable: '--font-calistoga'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${calistoga.variable} h-full antialiased`}
    >
      <body className="bg-gray-900 text-foreground font-sans">{children}</body>
    </html>
  );
}
